name: native_plugin
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.native_plugin
        pluginClass: NativePlugin
      ios:
        pluginClass: NativePlugin
